import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "@/lib/providers";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gadget Hub",
  description: "Generated by create next app",
};

// Define your auth options for next-auth
const authOptions = { /* your next-auth options here */ };

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Fetch the session
  const session = await getServerSession(authOptions); // Get session on the server

  return (
    <html lang="en">
      <body className={inter.className}>
          <Providers session={session}>
            <div>
              {children}
            </div>
          </Providers>
      </body>
    </html>
  );
}
