/* eslint-disable react-hooks/rules-of-hooks */
import NavBar from "@/app/(commonLayout)/components/shared/Navbar";
import type { Metadata } from "next";
import Sidebar from "./components/Sidebar/Sidebar";
import { getServerSession } from "next-auth";
import { authOptions } from "@/utils/authOptions";

export const metadata: Metadata = {
  title: "User Dashboard",
  description: "Generated by create next app",
};

export default async function userDashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <div>
      {/* Navbar */}
      {/* <NavBar session={session} /> */}

      <div className="fixed w-full z-50">
        <NavBar session={session}></NavBar>
      </div>

      {/* Layout with Sidebar and Main content */}
      <div className="relative md:flex">
        {/* Sidebar */}
        <Sidebar />

        {/* Main Content */}
        <main className="flex-1 p-5">{children}</main>
      </div>
    </div>
  );
}
